version: "3.8"
services:
  proxy:
    image: app-proxy:${PROXY_IMAGE_TAG:-latest}
    restart: on-failure
    container_name: proxy_container
    # depends_on:
      # - webapp
    ports:
      - "${PROXY_PORT:-9090}:80"
    # volumes:
    #   - appdata:/var/www/app:ro
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=localhost
      - NGINX_PROXY_SERVER=webapp:3000
      - STATIC_ROOT=/var/www/app/static

volumes:
  appdata:
    name: appdata